### ISSUE TITLE
Ajout sur le catalogue

### ISSUE THREAD

**Issue by orthagh** [departement-maine-et-loire/glpi-plugin-admincolor#1]
Bonjour @Nickyo0822

J'ai bien reçu la demande d'ajout de votre plugin au catalogue.
Juste une correction à apporter dans le noeud screenshots.
Il faut des url absolues pour que cela soit pris en compte par le site final.

Je laisse le plugin en attente de votre correction. "Pingez" moi quand c'est fait.
Cordialement.

**Comment by YannickComba** [comment]
Bonjour @orthagh , le XML a bien été modifié.
Cordialement.

**Comment by orthagh** [comment]
Activé sur le catalogue. Cela devrait etre effectif d'ici quelques heures.
