### ISSUE TITLE
Plugin ne fonctionne pas

### ISSUE THREAD

**Issue by ograttery** [departement-maine-et-loire/glpi-plugin-admincolor#3]
Bonjour,
J'ai installé votre plugin dans GLPI 10.0.11 mais celui-ci ne fonctionne pas (et ne fonctionnait pas plus en versions 10.0.10 ou 10.0.9 et inférieures).
J'ai bien accès à la configuration du plugin mais rien ne s'affiche quand je me connecte avec un utilisateur Admin ou Super-Admin.
De plus, il y a aussi un soucis dans le texte du plugin "Couleur de l'**arrère**-plan :" au lieu de "Couleur de l'**arrière**-plan :".
Merci pour votre prise en compte.
Olivier

**Comment by YannickComba** [comment]
Bonjour, 

Merci pour votre retour.

Effectivement cela était dû à un soucis de configuration côté plugin qui faisait qu'il n'avait pas le droit de voir certaines configurations suivant les droits du répertoire d'installation GLPI. Cela est désormais corrigé et sera disponible dans la version 1.0.1.
La coquille concernant le texte a aussi été corrigée.

Cordialement,

Yannick

**Comment by ograttery** [comment]
Bonjour,Merci pour votre réponse et prise en compte rapide.Cordialement,OlivierLe 2 janv. 2024 à 14:06, YannickComba ***@***.***> a écrit :﻿
Bonjour,
Merci pour votre retour.
Effectivement cela était dû à un soucis de configuration côté plugin qui faisait qu'il n'avait pas le droit de voir certaines configurations suivant les droits du répertoire d'installation GLPI. Cela est désormais corrigé et sera disponible dans la version 1.0.1.
La coquille concernant le texte a aussi été corrigée.
Cordialement,
Yannick
